server:
  port: 8001
spring:
  application:
    name: fund-payment-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url:  jdbc:mysql://localhost:3306/tran?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr:  124.220.36.202:8848
  kafka:
    bootstrap-servers:  121.43.116.232:9092
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: top.zynorl.transaction.fund.payment.serializer.TransactionRecordSerializer
      properties:
        linger.ms: 100

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto