server:
  port: 8002
spring:
  application:
    name: fund-collection-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/mq-transaction?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr:  localhost:8848
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mq-transaction-test
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: top.zynorl.transaction.fund.collection.deserializer.TransactionRecordDeserializer

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
